# CONFIGURACIÓN NETLIFY - FORZAR MIME TYPES
# Este archivo resuelve definitivamente el problema de HTML mostrado como texto

[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.18.0"

# HEADERS MUY ESPECÍFICOS - SIN POSIBILIDAD DE ERROR
[[headers]]
  for = "/ui/auth/index.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"

[[headers]]
  for = "/ui/auth/*"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-store, no-cache, must-revalidate"

[[headers]]
  for = "/critical-test.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-store"

[[headers]]
  for = "/**/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "no-store"

[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"

# REDIRECTS SIMPLES
[[redirects]]
  from = "/ui/auth"
  to = "/ui/auth/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
