# Deploy con configuración específica para MIME types
[build]
  base = "."
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.18.0"
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_OPTIONS = "--max-old-space-size=4096"

# Headers globales
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, Accept, Origin, X-Requested-With"

# CRÍTICO: Headers para HTML
[[headers]]
  for = "*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "public, max-age=0"

# Headers para archivos de UI específicos
[[headers]]
  for = "/ui/**/*.html"
  [headers.values]
    Content-Type = "text/html; charset=utf-8"
    Cache-Control = "public, max-age=0"

# Headers para JavaScript
[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

# Headers para JSON
[[headers]]
  for = "*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

# Headers para CSS
[[headers]]
  for = "*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"
    Cache-Control = "public, max-age=31536000"

# Redirects para API
[[redirects]]
  from = "/api/*"
  to = "https://api-superheroes-production.up.railway.app/:splat"
  status = 200

[[redirects]]
  from = "/auth/*"
  to = "https://api-superheroes-production.up.railway.app/auth/:splat"
  status = 200

# SPA redirects
[[redirects]]
  from = "/ui/auth/*"
  to = "/ui/auth/index.html"
  status = 200

[[redirects]]
  from = "/ui/heroes/*"
  to = "/ui/heroes/index.html"
  status = 200

[[redirects]]
  from = "/ui/villains/*"
  to = "/ui/villains/index.html"
  status = 200

[[redirects]]
  from = "/ui/teamBattles/*"
  to = "/ui/teamBattles/index.html"
  status = 200

# Catch-all para SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
